language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
install:
  - "pip install -r requirements.txt"
  - "python setup.py -q install"
script:
  - "cd json_preprocessor/test"
  - "python test_json_preprocessor.py"

